image: php:latest

pipelines:
  branches:
    master:
      - step:
          caches:
            - composer
          script:
            - apt-get update && apt-get install -y unzip openssh-client
            - mkdir -p ~/.ssh
            - scp -r $BITBUCKET_CLONE_DIR ubuntu@18.235.20.18:/var/www/telehealth_ frontend
            - ssh ubuntu@18.210.57.7 "cp /var/www/telehealth_frontend/.env.example /var/www/telehealth_frontend /.env && composer install -d /var/www/telehealth_frontend && sudo -S chmod -R 0755 /var/www/telehealth_frontend && sudo -S mv /var/www/telehealth_frontend /var/www/telehealth_frontend.old && sudo -S mv /var/www/telehealth_frontend /var/www && sudo -S chown -R www-data:www-data /var/www/telehealth_frontend && sudo -S rm -rf /var/www/telehealth_frontend.old"

